"""empty message

Revision ID: 92d18f8367d2
Revises: 
Create Date: 2019-07-27 16:45:33.921785

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '92d18f8367d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('NOT(station_id IS NOT NULL AND route_id IS NOT NULL)'),
    sa.CheckConstraint('NOT(station_id IS NULL AND route_id IS NULL)'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=False),
    sa.Column('end_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drone_route')
    op.drop_table('drone')
    op.drop_table('station')
    op.drop_table('route')
    # ### end Alembic commands ###
