"""empty message

Revision ID: bbabe721fbff
Revises: 92d18f8367d2
Create Date: 2019-07-27 20:24:46.218135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbabe721fbff'
down_revision = '92d18f8367d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drone', sa.Column('created_ts', sa.DateTime(), server_default=sa.func.utcnow(), nullable=False))
    op.add_column('drone', sa.Column('modified_ts', sa.DateTime(), nullable=True))
    op.add_column('route', sa.Column('created_ts', sa.DateTime(), server_default=sa.func.utcnow(), nullable=False))
    op.add_column('route', sa.Column('modified_ts', sa.DateTime(), nullable=True))
    op.drop_index('idx_route_path', table_name='route')
    op.add_column('station', sa.Column('created_ts', sa.DateTime(), server_default=sa.func.utcnow(), nullable=False))
    op.add_column('station', sa.Column('modified_ts', sa.DateTime(), nullable=True))
    op.drop_index('idx_station_geo', table_name='station')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_station_geo', 'station', ['geo'], unique=False)
    op.drop_column('station', 'modified_ts')
    op.drop_column('station', 'created_ts')
    op.create_index('idx_route_path', 'route', ['path'], unique=False)
    op.drop_column('route', 'modified_ts')
    op.drop_column('route', 'created_ts')
    op.drop_column('drone', 'modified_ts')
    op.drop_column('drone', 'created_ts')
    # ### end Alembic commands ###
