"""empty message

Revision ID: 51caca61b3ed
Revises: b25d029b19dc
Create Date: 2019-07-28 02:39:36.950352

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '51caca61b3ed'
down_revision = 'b25d029b19dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('points', sa.Text(), nullable=False))
    op.drop_index('idx_route_path', table_name='route')
    op.alter_column('station', 'geo',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT'),
               nullable=True)
    op.drop_index('idx_station_geo', table_name='station')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_station_geo', 'station', ['geo'], unique=False)
    op.alter_column('station', 'geo',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT'),
               nullable=False)
    op.create_index('idx_route_path', 'route', ['path'], unique=False)
    op.drop_column('route', 'points')
    # ### end Alembic commands ###